Homework2
angnobel/RHDEV-BE-2-flask pull request #9
Opened 2021-10-15 09:50 UTC by gabyang

Please have mercy, took me a while to figure this out

2021-10-26 16:25 UTC, codecodecoder78 requested changes

2021-10-26 16:25 UTC, nobelang78 commented on Auth/AuthAPI.py
> +from flask import jwt
Flask does not have jwt, just import jwt. We are using the package PyJWT which has the name signature jwt

2021-10-26 16:25 UTC, nobelang78 commented on main.py
> +# Write your flask code here
No code to start the server, look into app.run

2021-10-26 16:25 UTC, nobelang78 commented on Profiles/ProfilesAPI.py
> +@profiles_api.route("/profiles", methods = ["POST"])
/profiles already added as a prefix, this results in "/profiles/profiles" needed

2021-10-26 16:25 UTC, nobelang78 commented on Profiles/ProfilesAPI.py
> +    return "Wrong id" #What type of error should I throw in here
Should return a 404 not found error

2021-10-26 16:25 UTC, nobelang78 commented on Profiles/ProfilesAPI.py
> +    flash("Are you sure you want to delete profile?")
Flashing is not used. Flashing is to carry messages between request. RESTFUL APis do not do that. We simply return the data + message that the user requested

2021-10-26 16:25 UTC, nobelang78 commented on Profiles/ProfilesAPI.py
> +    return aboveMinScore
list cannot be returned, wrap in dict/jsonify

2021-10-26 16:25 UTC, nobelang78 commented on Auth/AuthAPI.py
> +    if (request.args.get("username") == None or request.args.get("hashedPassword") == None):
should be fromr request.form for form data in POST body

2021-10-26 16:25 UTC, nobelang78 commented on Auth/AuthAPI.py
> +        flash("login succesful")
can just reutrn login successful + a token in dict

2021-10-26 16:25 UTC, nobelang78 commented on Auth/AuthAPI.py
> +            return "login successful"
Should be 403 forbidden

2021-10-28 03:39 UTC, gabyang commented on Auth/AuthAPI.py
> +            return "login successful"
sorry, not so clear on this, what is forbidden? Do you mean the return string "Login Successful" should be "403 Forbidden"

2021-10-28 03:43 UTC, gabyang commented on Auth/AuthAPI.py
> +from flask import jwt
done

2021-10-28 03:43 UTC, gabyang commented on Profiles/ProfilesAPI.py
> +@profiles_api.route("/profiles", methods = ["POST"])
done

2021-10-28 03:43 UTC, gabyang commented on Profiles/ProfilesAPI.py
> +    return "Wrong id" #What type of error should I throw in here
done

2021-10-28 03:43 UTC, gabyang commented on Profiles/ProfilesAPI.py
> +    flash("Are you sure you want to delete profile?")
done

2021-11-29 02:59 UTC, angnobel commented on Auth/AuthAPI.py
> +            return "login successful"
Sorry, referring to the unsuccessful case. As this is a failed login, the status code for the return should be 403

2023-03-29 18:05 UTC, closed without merging